### ISSUE TITLE
Application Crash on Failed Model Download

### ISSUE THREAD

**Issue by crimsonleaf363** [OpenAgentsInc/onyx#40]
# Description:
The application consistently crashes when the model download fails, which results in an infinite crash loop. Upon launching the app, it immediately crashes without any opportunity for user interaction.

# Steps to Reproduce:
1. Attempt to download the model
2. If the download fails, the application will crash
3. Subsequent attempts to open the application will result in immediate crashes

Could this be connected to the open issue [#38](https://github.com/OpenAgentsInc/onyx/issues/38), which could be contributing to the download failure and crashes?

# Expected Behavior: 
The app should handle model download failures gracefully. The user should be provided with a detailed error message and an option to retry instead of crashing. 

# Environment:
- Device: Google Pixel running GrapheneOS
- Android Version: 15 (latest)
- Application Version: v0.0.1

**Comment by AtlantisPleb** [comment]
Excellent, thank you! Investigating now

**Comment by AtlantisPleb** [comment]
This issue should be fixed in the upcoming v0.0.2 release. We've made several significant improvements to the model download and initialization system:

1. Complete rewrite of model management:
   - Added proper state management with Zustand store
   - Better error handling and recovery
   - Proper cleanup of failed downloads
   - State persistence and validation

2. Technical improvements:
   - Switched from ReactNativeBlobUtil to expo-file-system for better reliability
   - Added proper error states and UI feedback
   - Better cleanup of partial downloads
   - Validation of model files before use
   - State recovery on app restart

3. User experience:
   - Clear download progress indicators
   - Better error messages
   - Ability to recover from failed states
   - No more infinite crash loops

Please try v0.0.2 when it's released and let us know if you still experience any crashes during model downloads. The new system should handle download failures gracefully with proper error messages instead of crashing.

(Comment from OpenAgents)

**Comment by AtlantisPleb** [comment]
Local models removed for now, closing for now - please reopen later if relevant
